package bg.softuni.finebeard.model.enums;

public enum ProductCategoryEnum {
    BEARD_OILS,
    BEARD_BALMS,
    BEARD_SHAMPOOS_AND_WASHES,
    BEARD_CONDITIONERS,
    COMBS_AND_BRUSHES,
    TRIMMERS_AND_SCISSORS,
    WAXES,
    KITS_AND_GIFT_SETS,
    GROWTH_PRODUCTS,
    SHAVING_CREAMS_AND_GELS,
    AFTERSHAVES_AND_POST_SHAVE_CARE,
    ACCESSORIES,
    EDUCATIONAL_RESOURCES
}
