version: "3"

services:
  finebeard:
    image: lirkoff/finebeard
    networks:
      - finebeard-network
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - REMEMBER_ME_KEY=${REMEMBER_ME_KEY}
      - APP_ID=${APP_ID}
      - GITHUB_CLIENT=${GITHUB_CLIENT}
      - GITHUB_SECRET=${GITHUB_SECRET}
      - RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY}
      - RECAPTCHA_SITE_SECRET=${RECAPTCHA_SITE_SECRET}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MASTER_PASS=${MASTER_PASS}
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
  database:
    image: mysql
    networks:
      - finebeard-network
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_HOST}
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    networks:
      - finebeard-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3001:3000'
    networks:
      - finebeard-network
    depends_on:
      - prometheus

networks:
  #  monitoring:
  #    driver: bridge
  finebeard-network:
    driver: bridge

