spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:}:3306/finebeard?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${MYSQL_USER:}
    password: ${MYSQL_PASSWORD:}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT:}
            client-secret: ${GITHUB_SECRET:}
            scope: user:email

  mvc:
    hiddenmethod:
      filter:
        enabled: true


logging:
  level:
#    org.springframework: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

open.exchange.rates:
  schema: https
  host: openexchangerates.org
  path: /api/latest.json
  app_id: ${APP_ID:test}
  symbols: EUR,BGN
  enabled: false

google.recaptcha:
  site: ${RECAPTCHA_SITE_KEY:test}
  secret: ${RECAPTCHA_SITE_SECRET:test}

mail:
  finebeard: "finebeard@example.com"
  host: "sandbox.smtp.mailtrap.io"
  port: 2525
  ssl: no
  tls: yes
  username: ${MAIL_USER}
  password: ${MAIL_PASSWORD}

finebeard:
  remember.me.key: ${REMEMBER_ME_KEY}
  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/

#server:
#  error:
#    include-message: always
#management:
#  server:
#    port: 8081
#  endpoints:
#    web:
#      base-path: /actuator
#      exposure:
#        include: "*"
