spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/finebeard?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  data:
    web:
      pageable:
        default-page-size: 4
        max-page-size: 10
  sql:
    init:
      mode: never

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT:}
            client-secret: ${GITHUB_SECRET:}
            scope: read:user

  mvc:
    hiddenmethod:
      filter:
        enabled: true


logging:
  level:
    org.springframework: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    io.github.resilience4j: DEBUG

open.exchange.rates:
  schema: https
  host: openexchangerates.org
  path: /api/latest.json
  app_id: ${APP_ID:test}
  symbols: EUR,BGN
  enabled: false

google.recaptcha:
  site: ${RECAPTCHA_SITE_KEY}
  secret: ${RECAPTCHA_SITE_SECRET}

mail:
  finebeard: "finebeard@example.com"
  host: "sandbox.smtp.mailtrap.io"
  port: 2525
  ssl: no
  tls: yes
  username: ${MAIL_USER}
  password: ${MAIL_PASSWORD}

finebeard:
  default.master.pass: ${MASTER_PASS:test}
  remember.me.key: ${REMEMBER_ME_KEY:test}
  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/

#server:
#  error:
#    include-message: always
management:
  server:
    port: 8080
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"

resilience4j.ratelimiter:
  instances:
    activate-user:
      limitForPeriod: 5
      limitRefreshPeriod: 1m
      timeoutDuration: 0